import { Donation } from './interfaces';
export const donations: Donation[] = [
  {
    id: 1,
    image: 'assets/donate2.jpg',
    heading: 'Feed 60 Kids for a month',
    subHeading: 'RAISING R30 000.00 BY 21 AUG',
    description: 'Feed-a-child, Cape Town',
    aboutImg: 'assets/food.jpg',
    cta: false,
    cta_url: '',
    popular: false,
    end: false,
    goal: 'R30 000',
    days: 30,
    progress: 85,
    contributions: 150,
  },
  {
    id: 2,
    image: 'assets/donate3.jpg',
    heading: 'Buy 5000 Blankets',
    subHeading: 'RAISING R8 000.00 BY 21 AUG',
    description: 'Drought fund, Durban',
    aboutImg: 'assets/donate7.jpg',
    cta: false,
    cta_url: '',
    popular: true,
    end: false,
    goal: 'R150 000',
    days: 8,
    progress: 45,
    contributions: 50,
  },
  {
    id: 3,
    image: 'assets/donate5.jpg',
    heading: 'Sponsor a farm with 1000 litres of water',
    subHeading: 'RAISING R30 000.00 BY 21 AUG',
    description: 'SPCA, Johannesburg',
    aboutImg: 'assets/donate4.jpg',
    cta: true,
    cta_url: '/about',
    end: true,
    popular: false,
    goal: 'R750 000',
    days: 30,
    progress: 35,
    contributions: 250,
  },
  {
    id: 4,
    image: 'assets/donate7.jpg',
    heading: 'Buy 5000 Blankets',
    subHeading: 'RAISING R8 000.00 BY 21 AUG',
    description: 'Drought fund, Durban',
    aboutImg: 'assets/blankets.jpg',
    cta: false,
    cta_url: '',
    popular: true,
    end: false,
    goal: 'R50 000',
    days: 8,
    progress: 60,
    contributions: 30,
  },
];